package com.qa.im.sqldatatypes;

public class Customer {
	private long id;
	private String forname;
	private String surname;

	/**
	 * This class contains all the variables needed for the Customers table fields
	 * The customer.id is generated by the SQL database
	 * @param forname
	 * @param surname
	 */
	
	public Customer(String forname, String surname) {
		super();
		this.forname = forname;
		this.surname = surname;
	}

	public Customer() {
		super();
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getForname() {
		return forname;
	}

	public void setForname(String forname) {
		this.forname = forname;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

}
