package com.qa.im.sqldatatypes;

public class Item {
	private long id;
	private String name;
	private double value;

	/**
	 * This class contains all the variables needed for the Items table fields
	 * The item.id is generated by the SQL database
	 * @param name
	 * @param value
	 */
	
	public Item(String name, double value) {
		super();
		this.name = name;
		this.value = value;
	}

	public Item() {
		super();
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getValue() {
		return value;
	}

	public void setValue(double value) {
		this.value = value;
	}

}
