package com.qa.im.sqldatatypes;

/**
 * This class contains all the variables needed for the Items table fields
 * The item.id is generated by the SQL database
 * @author Admin
 *
 */
public class Item {
	private int id;
	private String name;
	private double value;

	/**
	 * constructor for making new record
	 * @param name
	 * @param value
	 */
	
	public Item(String name, double value) {
		super();
		this.name = name;
		this.value = value;
	}

	/**
	 * constructor for reading from database
	 * @param id
	 * @param name
	 * @param value
	 */
	public Item(int id, String name, double value) {
		super();
		this.id = id;
		this.name = name;
		this.value = value;
	}
	
	public Item() {
		super();
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getValue() {
		return value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		long temp;
		temp = Double.doubleToLongBits(value);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Item other = (Item) obj;
		if (id != other.id)
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (Double.doubleToLongBits(value) != Double.doubleToLongBits(other.value))
			return false;
		return true;
	}

}
