package com.qa.im.sqldatatypes;

/**
 * This class contains all the variables needed for the item_orders table fields
 * The itemOrder.id is generated by the SQL database, if quantity is not given it defaults one
 * @author Admin
 *
 */
public class ItemOrder {
	private int id;
	private int itemID;
	private int orderID;
	private int quantity;

	
	/**
	 * constructor for reading from database
	 * @param id
	 * @param itemID
	 * @param orderID
	 * @param quantity
	 */
	public ItemOrder(int id, int itemID, int orderID, int quantity) {
		super();
		this.id = id;
		this.itemID = itemID;
		this.orderID = orderID;
		this.quantity = quantity;
	}
	
	/**
	 * constructor for making a new item order
	 * @param itemID
	 * @param orderID
	 * @param quantity
	 */
	public ItemOrder(int itemID, int orderID, int quantity) {
		super();
		this.itemID = itemID;
		this.orderID = orderID;
		this.quantity = quantity;
	}

	/**
	 * constructor where quantity will default to 1
	 * @param itemID
	 * @param orderID
	 */
	public ItemOrder(int itemID, int orderID) {
		super();
		this.itemID = itemID;
		this.orderID = orderID;
		this.quantity = 1;
	}

	public ItemOrder() {
		super();
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getItemID() {
		return itemID;
	}

	public void setItemID(int itemID) {
		this.itemID = itemID;
	}

	public int getOrderID() {
		return orderID;
	}

	public void setOrderID(int orderID) {
		this.orderID = orderID;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		result = prime * result + itemID;
		result = prime * result + orderID;
		result = prime * result + quantity;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ItemOrder other = (ItemOrder) obj;
		if (id != other.id)
			return false;
		if (itemID != other.itemID)
			return false;
		if (orderID != other.orderID)
			return false;
		if (quantity != other.quantity)
			return false;
		return true;
	}

}
