package com.qa.im.sqldatatypes;


/**
 * This class contains all the variables needed for the Orders table fields
 * The Order.id is generated by the SQL database, and the total is calculated after an item is added
 * @author Admin
 *
 */
public class Order {
	private int id;
	private int customer_id;
	private double total;

	/**
	 * Constructor for when we are creating a new order
	 * @param customer_id
	 */
	
	public Order(int customer_id) {
		super();
		this.customer_id = customer_id;
	}

	/**
	 * Constructor for when we are reading from the database
	 * @param id
	 * @param customer_id
	 * @param total
	 */
	public Order(int id, int customer_id, double total) {
		super();
		this.id = id;
		this.customer_id = customer_id;
		this.total = total;
	}
	
	public Order() {
		super();
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getCustomer_id() {
		return customer_id;
	}

	public void setCustomer_id(int customer_id) {
		this.customer_id = customer_id;
	}

	public double getTotal() {
		return total;
	}

	public void setTotal(double total) {
		this.total = total;
	}
}
