package com.qa.im.sqldatatypes;

public class Order {
	private long id;
	private long customer_id;
	private double total;

	/**
	 * This class contains all the variables needed for the Orders table fields
	 * The Order.id is generated by the SQL database, and the total is calculated when an item is added
	 * @param customer_id
	 */
	
	public Order(long customer_id) {
		super();
		this.customer_id = customer_id;
	}

	public Order() {
		super();
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getCustomer_id() {
		return customer_id;
	}

	public void setCustomer_id(long customer_id) {
		this.customer_id = customer_id;
	}

	public double getTotal() {
		return total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

}
