package com.qa.inventorymanagement;

public class itemOrder {
	private long id;
	private long itemID;
	private long orderID;
	private long quantity;

	/**
	 * This class contains all the variables needed for the item_orders table fields
	 * The itemOrder.id is generated by the SQL database, if quantity is not given it defaults zero
	 * @param itemID
	 * @param orderID
	 * @param quantity
	 */
	
	public itemOrder(long itemID, long orderID, long quantity) {
		super();
		this.itemID = itemID;
		this.orderID = orderID;
		this.quantity = quantity;
	}

	public itemOrder(long itemID, long orderID) {
		super();
		this.itemID = itemID;
		this.orderID = orderID;
		this.quantity = 0;
	}

	public itemOrder() {
		super();
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getItemID() {
		return itemID;
	}

	public void setItemID(long itemID) {
		this.itemID = itemID;
	}

	public long getOrderID() {
		return orderID;
	}

	public void setOrderID(long orderID) {
		this.orderID = orderID;
	}

	public long getQuantity() {
		return quantity;
	}

	public void setQuantity(long quantity) {
		this.quantity = quantity;
	}

}
